name: kitchensink-trigger

on:
  release:
    types: [published]

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://devdiv.visualstudio.com/OnlineServices
            azure-pipeline-name: 'generate-kitchensink-automated-TEST'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
